In [25]:
import numpy as np

In [48]:
#1
def Vandermonde_matrix(input_array ,no_of_col ,increase ):
    if increase == True:
        van_mat  = np.array([i**j for i in input_array for j in range(no_of_col)]).reshape(input_array.size,-1)
        return van_mat
    else :
        van_mat  = np.array([i**(no_of_col-1-j) for i in input_array for j in range(no_of_col)]).reshape(input_array.size,-1)    
        return van_mat
    
    
    

In [49]:
input_array=np.array([1,2,3,4])
no_of_col = 4
print("if increse true \n",Vandermonde_matrix(input_array,no_of_col,True))
print("if increse false \n",Vandermonde_matrix(input_array,no_of_col,False))

if increse true 
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
if increse false 
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [50]:
#2
input_arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
for i in range(len(input_arr)-k+1):
    print("y{} = {:.2f}".format(i+1,sum(input_arr[i:i+k])/k))
print('Thus, the moving average sequence has n-k+1={}-{}+1={} values'.format(len(input_arr),k,(len(input_arr)-k+1)))    

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
Thus, the moving average sequence has n-k+1=13-3+1=11 values
